language: python

python: 2.7

env:
    - TOXENV=py26-d16
    - TOXENV=py27-d16
    - TOXENV=py34-d16
    - TOXENV=py27-d17
    - TOXENV=py34-d17
    - TOXENV=py27-d18
    - TOXENV=py34-d18
    - TOXENV=cov

install: pip install --quiet --use-mirrors tox

script: tox

